import { render, screen, within } from "@testing-library/react";
import Pagination from "./Pagination";

type SetUpOptions = {
  totalCount: number;
  currentPage: number;
  limit?: number;
  pageGroupSize?: number;
};

function setUp({
  totalCount,
  currentPage,
  limit = 8,
  pageGroupSize = 5,
}: SetUpOptions) {
  return render(
    <Pagination
      totalCount={totalCount}
      currentPage={currentPage}
      limit={limit}
      pageGroupSize={pageGroupSize}
      createPageHref={(page) => `?page=${page}`}
    />,
  );
}

describe("Pagination", () => {
  describe("renders", () => {
    it("first page group buttons correctly", () => {
      setUp({ totalCount: 40, currentPage: 1 });
      expect(screen.getByRole("link", { name: "1" })).toBeInTheDocument();
      expect(screen.getByRole("link", { name: "2" })).toBeInTheDocument();
      expect(screen.getByRole("link", { name: "3" })).toBeInTheDocument();
      expect(screen.getByRole("link", { name: "4" })).toBeInTheDocument();
      expect(screen.getByRole("link", { name: "5" })).toBeInTheDocument();

      expect(screen.queryByRole("link", { name: "6" })).not.toBeInTheDocument();
    });

    it("second page group buttons correctly", () => {
      setUp({ totalCount: 50, currentPage: 6 });
      expect(screen.getByRole("link", { name: "6" })).toBeInTheDocument();
      expect(screen.getByRole("link", { name: "7" })).toBeInTheDocument();
      expect(screen.queryByRole("link", { name: "8" })).not.toBeInTheDocument();
      expect(screen.queryByRole("link", { name: "1" })).not.toBeInTheDocument();
    });

    it("no buttons when totalCount is 0", () => {
      const { container } = setUp({ totalCount: 0, currentPage: 1 });
      expect(within(container).queryAllByRole("link")).toHaveLength(0);
    });
  });

  it("uses href generated by createPageHref", () => {
    setUp({ totalCount: 40, currentPage: 1 });
    expect(screen.getByRole("link", { name: "1" })).toHaveAttribute(
      "href",
      "?page=1",
    );
  });

  describe("group tests: ", () => {
    it("hide prev-group arrows if first page group", () => {
      setUp({ totalCount: 40, currentPage: 1 });
      expect(
        screen.queryByRole("link", { name: /to previous page group/i }),
      ).not.toBeInTheDocument();
      expect(
        screen.queryByRole("link", { name: /to first page/i }),
      ).not.toBeInTheDocument();
    });

    it("hide next-group arrows if last page group", () => {
      setUp({ totalCount: 40, currentPage: 1 });
      expect(
        screen.queryByRole("link", { name: /to next page group/i }),
      ).not.toBeInTheDocument();
      expect(
        screen.queryByRole("link", { name: /to last page/i }),
      ).not.toBeInTheDocument();
    });

    it("show next-group arrows if not last page group", () => {
      setUp({ totalCount: 50, currentPage: 1 });
      expect(
        screen.getByRole("link", { name: /to next page group/i }),
      ).toBeInTheDocument();
      expect(
        screen.getByRole("link", { name: /to last page/i }),
      ).toBeInTheDocument();
    });

    it("show prev-group arrows if not first page group", () => {
      setUp({ totalCount: 50, currentPage: 6 });
      expect(
        screen.getByRole("link", { name: /to previous page group/i }),
      ).toBeInTheDocument();
      expect(
        screen.getByRole("link", { name: /to first page/i }),
      ).toBeInTheDocument();
    });
  });
});
